name: chatbot
version: 0.3.5+15
description: ChatBot

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^1.2.2
  intl: ^0.19.0
  archive: ^4.0.2

  animate_do: ^3.3.4
  flutter_svg: ^2.0.16
  flutter_spinkit: ^5.2.1
  flutter_riverpod: ^2.6.1

  markdown: ^7.2.2
  flutter_math_fork: ^0.7.2
  flutter_markdown: ^0.7.4+2
  flutter_highlighter: ^0.1.1

  file_picker: ^8.1.4
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  flutter_image_compress: ^2.3.0

  langchain: ^0.7.7+2
  langchain_core: ^0.3.6+1
  langchain_openai: ^0.7.3
  langchain_google: ^0.6.4+2
  langchain_community: ^0.3.3

  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3

  screenshot: ^3.0.0
  share_plus: ^10.1.2
  url_launcher: ^6.3.1
  audioplayers: ^6.1.0
  package_info_plus: ^8.1.2
  beautiful_soup_dart: ^0.3.0
  image_gallery_saver_plus: ^3.0.5

  
dependency_overrides:
  path: 1.9.1

dev_dependencies:
  intl_utils: ^2.8.8
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.0.3

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/gen
